# Generated by Django 4.0.8 on 2023-01-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hodnota', models.CharField(max_length=255)),
            ],
        ),
    ]
