# Generated by Django 4.0.8 on 2023-01-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_attributevalue_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('products_ids', models.JSONField()),
            ],
        ),
    ]
